{% set version = "3.18.14" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bma
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BMA_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BMA/BMA_{{ version }}.tar.gz
  sha256: 3bc0fd44001c5817dc6a8eda9fb266967407f8a05ac0a5c05b10c87df462cb23

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-inline
    - r-leaps
    - r-robustbase
    - r-rrcov
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-inline
    - r-leaps
    - r-robustbase
    - r-rrcov
    - r-survival

test:
  commands:
    - $R -e "library('BMA')"           # [not win]
    - "\"%R%\" -e \"library('BMA')\""  # [win]

about:
  home: http://stats.research.att.com/volinsky/bma.html
  license: GPL-2.0-or-later
  summary: Package for Bayesian model averaging and variable selection for linear models, generalized linear models and survival models (cox regression).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: BMA
# Version: 3.18.9
# Date: 2018-09-07
# Title: Bayesian Model Averaging
# Author: Adrian Raftery <raftery@uw.edu>, Jennifer Hoeting, Chris Volinsky, Ian Painter, Ka Yee Yeung
# Maintainer: Hana Sevcikova <hanas@uw.edu>
# Description: Package for Bayesian model averaging and variable selection for linear models, generalized linear models and survival models (cox regression).
# Depends: survival, leaps, robustbase, inline, rrcov
# Imports: methods
# Suggests: MASS
# License: GPL (>= 2)
# URL: http://stats.research.att.com/volinsky/bma.html
# NeedsCompilation: yes
# Packaged: 2018-09-07 19:03:17 UTC; hana
# Repository: CRAN
# Date/Publication: 2018-09-14 07:50:13 UTC
