{% set version = "3.18.8" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bma
  version: {{ version|replace("-", "_") }}

source:
  fn: BMA_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/BMA_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/BMA/BMA_{{ version }}.tar.gz
  sha256: 05c6e0613cb859b7d237b3a2433ca901b1cef0fe66f704db1fabfa132c7c62a8

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-inline
    - r-leaps
    - r-robustbase
    - r-rrcov
    - r-survival
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-inline
    - r-leaps
    - r-robustbase
    - r-rrcov
    - r-survival
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('BMA')"  # [not win]
    - "\"%R%\" -e \"library('BMA')\""  # [win]

about:
  home: http://www.research.att.com/~volinsky/bma.html
  license: GPL (>= 2)
  summary: Package for Bayesian model averaging and variable selection for linear models, generalized
    linear models and survival models (cox regression).
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
